// hydra `blend` -- type: combine
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: amount (0.5)

uniform float amount;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 blend(vec4 _c0, vec4 _c1, float amount) {
   return _c0*(1.0-amount)+_c1*amount;
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);   // source
   vec4 c1 = texture(sTD2DInputs[1], vUV.st);   // with
   fragColor = TDOutputSwizzle(blend(c0, c1, amount));
}
