// hydra `color` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: r (1.0), g (1.0), b (1.0), a (1.0)

uniform float r;
uniform float g;
uniform float b;
uniform float a;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 color(vec4 _c0, float r, float g, float b, float a) {
   vec4 c = vec4(r, g, b, a);
   vec4 pos = step(0.0, c); // detect whether negative
   // if > 0, return r * _c0
   // if < 0 return (1.0-r) * _c0
   return vec4(mix((1.0-_c0)*abs(c), c*_c0, pos));
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(color(c0, r, g, b, a));
}
