// hydra `contrast` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: amount (1.6)

uniform float amount;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 contrast(vec4 _c0, float amount) {
   vec4 c = (_c0-vec4(0.5))*vec4(amount) + vec4(0.5);
   return vec4(c.rgb, _c0.a);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(contrast(c0, amount));
}
