// hydra `diff` -- type: combine
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 diff(vec4 _c0, vec4 _c1) {
   return vec4(abs(_c0.rgb-_c1.rgb), max(_c0.a, _c1.a));
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);   // source
   vec4 c1 = texture(sTD2DInputs[1], vUV.st);   // with
   fragColor = TDOutputSwizzle(diff(c0, c1));
}
