// hydra `gradient` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: speed (0.0)

uniform float time;          // -> absTime.seconds
uniform float speed;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 gradient(vec2 _st, float speed) {
   return vec4(_st, sin(time*speed), 1.0);
}

void main() {
   fragColor = TDOutputSwizzle(gradient(vUV.st, speed));
}
