// hydra `invert` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: amount (1.0)

uniform float amount;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 invert(vec4 _c0, float amount) {
   return vec4((1.0-_c0.rgb)*amount + _c0.rgb*(1.0-amount), _c0.a);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(invert(c0, amount));
}
