// hydra `kaleid` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: nSides (4.0)

uniform float uvmode;        // -> Pipeline page, mode
uniform float nSides;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 kaleid(vec2 _st, float nSides) {
   vec2 st = _st;
   st -= 0.5;
   float r = length(st);
   float a = atan(st.y, st.x);
   float pi = 2.*3.1416;
   a = mod(a,pi/nSides);
   a = abs(a-pi/nSides/2.);
   return r*vec2(cos(a), sin(a));
}

void main() {
   if (uvmode > 0.5) {
      // transform the incoming coordinate map; a source evaluates it downstream
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      fragColor = TDOutputSwizzle(vec4(kaleid(inSt, nSides), 0.0, 1.0));
   } else {
      // image mode: sample the input at the transformed coordinate
      vec2 st = kaleid(vUV.st, nSides);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
   }
}
