// hydra `mask` -- type: combine
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.

out vec4 fragColor;

// --- _luminance, from hydra utility-functions.js ---
float _luminance(vec3 rgb){
  const vec3 W = vec3(0.2125, 0.7154, 0.0721);
  return dot(rgb, W);
}

// --- body verbatim from hydra glsl-functions.js ---
vec4 mask(vec4 _c0, vec4 _c1) {
   float a = _luminance(_c1.rgb);
  return vec4(_c0.rgb*a, a*_c0.a);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);   // source
   vec4 c1 = texture(sTD2DInputs[1], vUV.st);   // with
   fragColor = TDOutputSwizzle(mask(c0, c1));
}
