// hydra `modulateHue` -- type: combineCoord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: amount (1.0)

uniform vec2 resolution;     // -> me.width, me.height
uniform float uvmode;        // -> Pipeline page, mode
uniform float amount;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 modulateHue(vec2 _st, vec4 _c0, float amount) {
   return _st + (vec2(_c0.g - _c0.r, _c0.b - _c0.g) * amount * 1.0/resolution);
}

void main() {
   if (uvmode > 0.5) {
      // input 0 carries coordinates, not an image. hydra samples the modulator
      // at the uv as it stands here -- i.e. after the coord ops that come later
      // in the chain, which is exactly what arrives on input 0.
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      vec4 c0 = texture(sTD2DInputs[1], fract(inSt));
      fragColor = TDOutputSwizzle(vec4(modulateHue(inSt, c0, amount), 0.0, 1.0));
   } else {
      vec2 st = vUV.st;
      vec4 c0 = texture(sTD2DInputs[1], st);    // modulator (hydra's _c0)
      vec2 st2 = modulateHue(st, c0, amount);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st2)));
   }
}
