// hydra `modulateKaleid` -- type: combineCoord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: nSides (4.0)

uniform float nSides;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 modulateKaleid(vec2 _st, vec4 _c0, float nSides) {
   vec2 st = _st - 0.5;
   float r = length(st);
   float a = atan(st.y, st.x);
   float pi = 2.*3.1416;
   a = mod(a,pi/nSides);
   a = abs(a-pi/nSides/2.);
   return (_c0.r+r)*vec2(cos(a), sin(a));
}

void main() {
   vec2 st = vUV.st;
   vec4 c0 = texture(sTD2DInputs[1], st);       // modulator (hydra's _c0)
   vec2 st2 = modulateKaleid(st, c0, nSides);
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st2)));
}
