// hydra `modulateScrollY` -- type: combineCoord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: scrollY (0.5), speed (0.0)

uniform float time;          // -> absTime.seconds
uniform float scrollY;
uniform float speed;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 modulateScrollY(vec2 _st, vec4 _c0, float scrollY, float speed) {
   _st.y += _c0.r*scrollY + time*speed;
   return fract(_st);
}

void main() {
   vec2 st = vUV.st;
   vec4 c0 = texture(sTD2DInputs[1], st);       // modulator (hydra's _c0)
   vec2 st2 = modulateScrollY(st, c0, scrollY, speed);
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st2)));
}
