// hydra `modulatePixelate` -- type: combineCoord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: multiple (10.0), offset (3.0)

uniform float uvmode;        // -> Pipeline page, mode
uniform float multiple;
uniform float offset;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 modulatePixelate(vec2 _st, vec4 _c0, float multiple, float offset) {
   vec2 xy = vec2(offset + _c0.x*multiple, offset + _c0.y*multiple);
   return (floor(_st * xy) + 0.5)/xy;
}

void main() {
   if (uvmode > 0.5) {
      // input 0 carries coordinates, not an image. hydra samples the modulator
      // at the uv as it stands here -- i.e. after the coord ops that come later
      // in the chain, which is exactly what arrives on input 0.
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      vec4 c0 = texture(sTD2DInputs[1], fract(inSt));
      fragColor = TDOutputSwizzle(vec4(modulatePixelate(inSt, c0, multiple, offset), 0.0, 1.0));
   } else {
      vec2 st = vUV.st;
      vec4 c0 = texture(sTD2DInputs[1], st);    // modulator (hydra's _c0)
      vec2 st2 = modulatePixelate(st, c0, multiple, offset);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st2)));
   }
}
