// hydra `modulateRepeatX` -- type: combineCoord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: reps (3.0), offset (0.5)

uniform float uvmode;        // -> Pipeline page, mode
uniform float reps;
uniform float offset;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 modulateRepeatX(vec2 _st, vec4 _c0, float reps, float offset) {
   vec2 st = _st * vec2(reps, 1.0);
   //  float f =  mod(_st.y,2.0);
   st.y += step(1., mod(st.x,2.0)) + _c0.r * offset;
   return fract(st);
}

void main() {
   if (uvmode > 0.5) {
      // input 0 carries coordinates, not an image. hydra samples the modulator
      // at the uv as it stands here -- i.e. after the coord ops that come later
      // in the chain, which is exactly what arrives on input 0.
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      vec4 c0 = texture(sTD2DInputs[1], fract(inSt));
      fragColor = TDOutputSwizzle(vec4(modulateRepeatX(inSt, c0, reps, offset), 0.0, 1.0));
   } else {
      vec2 st = vUV.st;
      vec4 c0 = texture(sTD2DInputs[1], st);    // modulator (hydra's _c0)
      vec2 st2 = modulateRepeatX(st, c0, reps, offset);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st2)));
   }
}
