// hydra `osc` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: frequency (60.0), sync (0.1), offset (0.0)

uniform float time;          // -> absTime.seconds
uniform float uvmode;        // -> parent().par.Coordmode
uniform float frequency;
uniform float sync;
uniform float offset;

#define COORD_IN 0

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 osc(vec2 _st, float frequency, float sync, float offset) {
   vec2 st = _st;
   float r = sin((st.x-offset/frequency+time*sync)*frequency)*0.5  + 0.5;
   float g = sin((st.x+time*sync)*frequency)*0.5 + 0.5;
   float b = sin((st.x+offset/frequency+time*sync)*frequency)*0.5  + 0.5;
   return vec4(r, g, b, 1.0);
}

void main() {
   vec2 st = vUV.st;
   if (uvmode > 0.5) st = texture(sTD2DInputs[COORD_IN], vUV.st).rg;
   fragColor = TDOutputSwizzle(osc(st, frequency, sync, offset));
}
