// hydra `pixelate` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: pixelX (20.0), pixelY (20.0)

uniform float uvmode;        // -> Pipeline page, mode
uniform float pixelX;
uniform float pixelY;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 pixelate(vec2 _st, float pixelX, float pixelY) {
   vec2 xy = vec2(pixelX, pixelY);
   return (floor(_st * xy) + 0.5)/xy;
}

void main() {
   if (uvmode > 0.5) {
      // transform the incoming coordinate map; a source evaluates it downstream
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      fragColor = TDOutputSwizzle(vec4(pixelate(inSt, pixelX, pixelY), 0.0, 1.0));
   } else {
      // image mode: sample the input at the transformed coordinate
      vec2 st = pixelate(vUV.st, pixelX, pixelY);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
   }
}
