// hydra `pixelate` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: pixelX (20.0), pixelY (20.0)

uniform float pixelX;
uniform float pixelY;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 pixelate(vec2 _st, float pixelX, float pixelY) {
   vec2 xy = vec2(pixelX, pixelY);
   return (floor(_st * xy) + 0.5)/xy;
}

void main() {
   // a coord node samples its input at the transformed coordinate;
   // fract() stands in for hydra's wrap, which happens inside src()/prev()
   vec2 st = pixelate(vUV.st, pixelX, pixelY);
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
}
