// hydra `posterize` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: bins (3.0), gamma (0.6)

uniform float bins;
uniform float gamma;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 posterize(vec4 _c0, float bins, float gamma) {
   vec4 c2 = pow(_c0, vec4(gamma));
   c2 *= vec4(bins);
   c2 = floor(c2);
   c2/= vec4(bins);
   c2 = pow(c2, vec4(1.0/gamma));
   return vec4(c2.xyz, _c0.a);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(posterize(c0, bins, gamma));
}
