// hydra `prev` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.

uniform float uvmode;        // -> parent().par.Coordmode

#define COORD_IN 1

#define prevBuffer sTD2DInputs[0]

#define texture2D texture

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 prev(vec2 _st) {
   return texture2D(prevBuffer, fract(_st));
}

void main() {
   vec2 st = vUV.st;
   if (uvmode > 0.5) st = texture(sTD2DInputs[COORD_IN], vUV.st).rg;
   fragColor = TDOutputSwizzle(prev(st));
}
