// hydra `prev` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.

#define prevBuffer sTD2DInputs[0]

#define texture2D texture

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 prev(vec2 _st) {
   return texture2D(prevBuffer, fract(_st));
}

void main() {
   fragColor = TDOutputSwizzle(prev(vUV.st));
}
