// hydra `r` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: scale (1.0), offset (0.0)

uniform float scale;
uniform float offset;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 r(vec4 _c0, float scale, float offset) {
   return vec4(_c0.r * scale + offset);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(r(c0, scale, offset));
}
