// hydra `repeatY` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: reps (3.0), offset (0.0)

uniform float reps;
uniform float offset;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 repeatY(vec2 _st, float reps, float offset) {
   vec2 st = _st * vec2(1.0, reps);
   //  float f =  mod(_st.y,2.0);
   st.x += step(1., mod(st.y,2.0))* offset;
   return fract(st);
}

void main() {
   // a coord node samples its input at the transformed coordinate;
   // fract() stands in for hydra's wrap, which happens inside src()/prev()
   vec2 st = repeatY(vUV.st, reps, offset);
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
}
