// hydra `repeatX` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: reps (3.0), offset (0.0)

uniform float uvmode;        // -> Pipeline page, mode
uniform float reps;
uniform float offset;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 repeatX(vec2 _st, float reps, float offset) {
   vec2 st = _st * vec2(reps, 1.0);
   //  float f =  mod(_st.y,2.0);
   st.y += step(1., mod(st.x,2.0))* offset;
   return fract(st);
}

void main() {
   if (uvmode > 0.5) {
      // transform the incoming coordinate map; a source evaluates it downstream
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      fragColor = TDOutputSwizzle(vec4(repeatX(inSt, reps, offset), 0.0, 1.0));
   } else {
      // image mode: sample the input at the transformed coordinate
      vec2 st = repeatX(vUV.st, reps, offset);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
   }
}
