// hydra `repeat` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: repeatX (3.0), repeatY (3.0), offsetX (0.0), offsetY (0.0)

uniform float uvmode;        // -> Pipeline page, mode
uniform float repeatX;
uniform float repeatY;
uniform float offsetX;
uniform float offsetY;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 repeat(vec2 _st, float repeatX, float repeatY, float offsetX, float offsetY) {
   vec2 st = _st * vec2(repeatX, repeatY);
   st.x += step(1., mod(st.y,2.0)) * offsetX;
   st.y += step(1., mod(st.x,2.0)) * offsetY;
   return fract(st);
}

void main() {
   if (uvmode > 0.5) {
      // transform the incoming coordinate map; a source evaluates it downstream
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      fragColor = TDOutputSwizzle(vec4(repeat(inSt, repeatX, repeatY, offsetX, offsetY), 0.0, 1.0));
   } else {
      // image mode: sample the input at the transformed coordinate
      vec2 st = repeat(vUV.st, repeatX, repeatY, offsetX, offsetY);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
   }
}
