// hydra `rotate` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: angle (10.0), speed (0.0)

uniform float time;          // -> absTime.seconds
uniform float uvmode;        // -> Pipeline page, mode
uniform float angle;
uniform float speed;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 rotate(vec2 _st, float angle, float speed) {
   vec2 xy = _st - vec2(0.5);
   float ang = angle + speed *time;
   xy = mat2(cos(ang),-sin(ang), sin(ang),cos(ang))*xy;
   xy += 0.5;
   return xy;
}

void main() {
   if (uvmode > 0.5) {
      // transform the incoming coordinate map; a source evaluates it downstream
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      fragColor = TDOutputSwizzle(vec4(rotate(inSt, angle, speed), 0.0, 1.0));
   } else {
      // image mode: sample the input at the transformed coordinate
      vec2 st = rotate(vUV.st, angle, speed);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
   }
}
