// hydra `saturate` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: amount (2.0)

uniform float amount;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 saturate(vec4 _c0, float amount) {
   const vec3 W = vec3(0.2125, 0.7154, 0.0721);
   vec3 intensity = vec3(dot(_c0.rgb, W));
   return vec4(mix(intensity, _c0.rgb, amount), _c0.a);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(saturate(c0, amount));
}
