// hydra `scale` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: amount (1.5), xMult (1.0), yMult (1.0), offsetX (0.5), offsetY (0.5)

uniform float uvmode;        // -> Pipeline page, mode
uniform float amount;
uniform float xMult;
uniform float yMult;
uniform float offsetX;
uniform float offsetY;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 scale(vec2 _st, float amount, float xMult, float yMult, float offsetX, float offsetY) {
   vec2 xy = _st - vec2(offsetX, offsetY);
   xy*=(1.0/vec2(amount*xMult, amount*yMult));
   xy+=vec2(offsetX, offsetY);
   return xy;
}

void main() {
   if (uvmode > 0.5) {
      // transform the incoming coordinate map; a source evaluates it downstream
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      fragColor = TDOutputSwizzle(vec4(scale(inSt, amount, xMult, yMult, offsetX, offsetY), 0.0, 1.0));
   } else {
      // image mode: sample the input at the transformed coordinate
      vec2 st = scale(vUV.st, amount, xMult, yMult, offsetX, offsetY);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
   }
}
