// hydra `scrollY` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: scrollY (0.5), speed (0.0)

uniform float time;          // -> absTime.seconds
uniform float scrollY;
uniform float speed;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 scrollY(vec2 _st, float scrollY, float speed) {
   _st.y += scrollY + time*speed;
   return fract(_st);
}

void main() {
   // a coord node samples its input at the transformed coordinate;
   // fract() stands in for hydra's wrap, which happens inside src()/prev()
   vec2 st = scrollY(vUV.st, scrollY, speed);
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
}
