// hydra `scroll` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: scrollX (0.5), scrollY (0.5), speedX (0.0), speedY (0.0)

uniform float time;          // -> absTime.seconds
uniform float uvmode;        // -> Pipeline page, mode
uniform float scrollX;
uniform float scrollY;
uniform float speedX;
uniform float speedY;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 scroll(vec2 _st, float scrollX, float scrollY, float speedX, float speedY) {

   _st.x += scrollX + time*speedX;
   _st.y += scrollY + time*speedY;
   return fract(_st);
}

void main() {
   if (uvmode > 0.5) {
      // transform the incoming coordinate map; a source evaluates it downstream
      vec2 inSt = texture(sTD2DInputs[0], vUV.st).rg;
      fragColor = TDOutputSwizzle(vec4(scroll(inSt, scrollX, scrollY, speedX, speedY), 0.0, 1.0));
   } else {
      // image mode: sample the input at the transformed coordinate
      vec2 st = scroll(vUV.st, scrollX, scrollY, speedX, speedY);
      fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
   }
}
