// hydra `scrollX` -- type: coord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: scrollX (0.5), speed (0.0)

uniform float time;          // -> absTime.seconds
uniform float scrollX;
uniform float speed;

out vec4 fragColor;

// renamed from `scrollX`: an argument shares that name
// --- body verbatim from hydra glsl-functions.js ---
vec2 hydra_scrollX(vec2 _st, float scrollX, float speed) {
   _st.x += scrollX + time*speed;
   return fract(_st);
}

void main() {
   // a coord node samples its input at the transformed coordinate;
   // fract() stands in for hydra's wrap, which happens inside src()/prev()
   vec2 st = hydra_scrollX(vUV.st, scrollX, speed);
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
}
