// hydra `shape` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: sides (3.0), radius (0.3), smoothing (0.01)

uniform float sides;
uniform float radius;
uniform float smoothing;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 shape(vec2 _st, float sides, float radius, float smoothing) {
   vec2 st = _st * 2. - 1.;
   // Angle and radius from the current pixel
   float a = atan(st.x,st.y)+3.1416;
   float r = (2.*3.1416)/sides;
   float d = cos(floor(.5+a/r)*r-a)*length(st);
   return vec4(vec3(1.0-smoothstep(radius,radius + smoothing + 0.0000001,d)), 1.0);
}

void main() {
   fragColor = TDOutputSwizzle(shape(vUV.st, sides, radius, smoothing));
}
