// hydra `shift` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: r (0.5), g (0.0), b (0.0), a (0.0)

uniform float r;
uniform float g;
uniform float b;
uniform float a;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 shift(vec4 _c0, float r, float g, float b, float a) {
   vec4 c2 = vec4(_c0);
   c2.r += fract(r);
   c2.g += fract(g);
   c2.b += fract(b);
   c2.a += fract(a);
   return vec4(c2.rgba);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(shift(c0, r, g, b, a));
}
