// hydra `solid` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: r (0.0), g (0.0), b (0.0), a (1.0)

uniform float uvmode;        // -> Pipeline page, mode
uniform float r;
uniform float g;
uniform float b;
uniform float a;

#define COORD_IN 0

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 solid(vec2 _st, float r, float g, float b, float a) {
   return vec4(r, g, b, a);
}

void main() {
   vec2 st = vUV.st;
   if (uvmode > 0.5) st = texture(sTD2DInputs[COORD_IN], vUV.st).rg;
   fragColor = TDOutputSwizzle(solid(st, r, g, b, a));
}
