// hydra `src` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: tex (null)

uniform float uvmode;        // -> Pipeline page, mode

#define COORD_IN 1

#define tex sTD2DInputs[0]

#define texture2D texture

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 src(vec2 _st) {
   //  vec2 uv = gl_FragCoord.xy/vec2(1280., 720.);
   return texture2D(tex, fract(_st));
}

void main() {
   vec2 st = vUV.st;
   if (uvmode > 0.5) st = texture(sTD2DInputs[COORD_IN], vUV.st).rg;
   fragColor = TDOutputSwizzle(src(st));
}
