// hydra `brightness` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: amount (0.4)

uniform float amount;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 brightness(vec4 _c0, float amount) {
   return vec4(_c0.rgb + vec3(amount), _c0.a);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(brightness(c0, amount));
}
