"""Build one Base COMP per hydra function, wrapping a GLSL TOP and its shader.

Each component:

    hydra_osc/
      source, modulator   In TOPs    (class-dependent; none for `src`)
      frequency, sync...  In CHOPs   (one per numeric hydra argument)
      frequency_default   Constant CHOPs, wired to input 1 of the matching In CHOP
      pixel               Text DAT   (generated by `compile` -- not a file)
      glsl                GLSL TOP   (internals -- users never open this)
      out                 Out TOP    (also the component's Operator Viewer)
      compile             Text DAT   (hydra_compile.py, embedded)
      chain_exec, mode_exec, time_exec   callbacks
    + custom pages Hydra, Pipeline, Time Sync, Output, Version

Argument resolution, per input:

    Each numeric argument gets its own CHOP input on the component, named after
    the hydra argument. Whatever channel you connect is used -- the name does not
    matter, only the connector. With nothing connected, the In CHOP falls through
    to its second input, a Constant CHOP driven by the component's custom
    parameter. So: connect a CHOP to animate, or leave it and dial the parameter.

    The parameter may itself hold any expression, including
    mod('/project1/hydra/hydra_seq').val([...]) for hydra's array arguments.

The shader is never a file: each component stores its function's spec on itself
(`hydra_spec`) and its embedded `compile` module generates the shader from that
-- alone in Image mode, fused with its upstream chain in Compiled mode.

Run from the Textport once a Text DAT is synced to this file:

    b = mod('/project1/hydra/build_hydra')
    b.build_all(op('/project1/hydra'))     # build (replaces same-named components)
    b.rebuild(op('/project1/hydra'))       # wipe everything generated, then build
    b.clear(op('/project1/hydra'))         # wipe only
    b.upgrade(op('/project1'))             # bring placed copies up to date
    b.layout_groups(op('/project1/hydra'), b.load_specs())   # re-arrange only

`clear` and `rebuild` destroy every hydra_* component AND every Annotate COMP in
the target container -- keep these in their own container, not next to work you
care about.
"""

import hashlib
import json
import os
import re
import time

HERE = 'assets/scripts/hydra'
TOX_ROOT = 'components/hydra'   # exported .tox tree, one folder per group
HYDRA_TAG = 'hydra'             # marks generated components; survives .tox save
DEFAULT_RES = (1280, 720)       # source components; everything else follows its input
NONCOMMERCIAL_MAX = 1280        # the free licence caps output at 1280x1280

# Shown on every component's Version page. Bump on every change to this file,
# hydra_compile.py or hydra-utils.glsl -- it is how a placed copy says which
# code it was built from. The Compiler hash on that page changes by itself.
VERSION = '0.2.1'

# custom pages, in the order every component should show them
PAGE_ORDER = ('Hydra', 'Pipeline', 'Time Sync', 'Output', 'Version')

MODES = (('compiled', 'Compiled'), ('image', 'Image'))     # first is the default

# image inputs per hydra function class; `source` is always input 0
CLASS_INPUTS = {
    'src':          [],
    'coord':        ['source'],
    'color':        ['source'],
    'combine':      ['source', 'with'],
    'combineCoord': ['source', 'modulator'],   # modulator is hydra's _c0
}

# functions whose class says "no image input" but whose body samples a texture:
# `src` takes an external TOP, `prev` takes the feedback of the chain's output
NAME_INPUTS = {
    'src':  ['source'],
    'prev': ['source'],
}
TEXTURE_ALIAS = {'src': 'tex', 'prev': 'prevBuffer'}   # the sampler they name

UTILS = ('_luminance', '_noise', '_rgbToHsv', '_hsvToRgb')


def inputs_for(spec):
    return NAME_INPUTS.get(spec['name'], CLASS_INPUTS[spec['type']])


def uses_of(spec):
    """Which of hydra's globals the function body reads."""
    return [w for w in ('time', 'resolution')
            if re.search(rf'\b{w}\b', spec.get('glsl', ''))]


# hydra's documentation groups are exactly its five GLSL classes. Colours are
# eyeballed from the docs' underlines; `src` is a guess (that group is cropped
# in the screenshot I worked from) -- adjust to taste, it is only cosmetic.
GROUPS = {
    'src':          ('Source',   (0.96, 0.62, 0.42)),   # orange
    'coord':        ('Geometry', (0.95, 0.82, 0.42)),   # yellow
    'color':        ('Color',    (0.71, 0.91, 0.33)),   # lime
    'combine':      ('Blend',    (0.44, 0.90, 0.63)),   # green
    'combineCoord': ('Modulate', (0.50, 0.91, 0.88)),   # cyan
    'audio':        ('Audio',    (0.94, 0.38, 0.60)),   # pink
}

GROUP_ORDER = ('src', 'coord', 'color', 'combine', 'combineCoord', 'audio')

# components that are not generated from hydra-functions.json, by group
EXTRA_MEMBERS = {'audio': [{'name': 'fft', 'type': 'audio'}]}

CELL_W, CELL_H = 240, 200      # spacing between components
COLS = 6                       # components per row within a group
PAD = 80                       # annotation margin around a group

# the slice, used when hydra-functions.json is not present yet
SLICE = [
    {'name': 'osc', 'type': 'src', 'glsl': '', 'inputs': [
        {'name': 'frequency', 'type': 'float', 'default': 60},
        {'name': 'sync', 'type': 'float', 'default': 0.1},
        {'name': 'offset', 'type': 'float', 'default': 0}]},
    {'name': 'rotate', 'type': 'coord', 'glsl': '', 'inputs': [
        {'name': 'angle', 'type': 'float', 'default': 10},
        {'name': 'speed', 'type': 'float', 'default': 0}]},
]


# --- small TD helpers -------------------------------------------------------------

def par_name(hydra_name):
    """repeatX -> Repeatx. TD custom par names are Capitalized alphanumerics."""
    return hydra_name[0].upper() + hydra_name[1:].lower()


def set_menu(par, *needles):
    for i, n in enumerate(par.menuNames):
        if all(x in n.lower() for x in needles):
            par.menuIndex = i
            return n
    print(f'  !! {par.name}: no match for {needles} in {par.menuNames}')


def find_par(o, *candidates):
    """First existing par among `candidates`; prints what is there if none match."""
    names = {p.name for p in o.pars()}
    for c in candidates:
        if c in names:
            return o.par[c]
    print(f'  !! {o.path}: none of {candidates} in {sorted(names)}')
    return None


def custom_names(comp):
    return {p.name for p in comp.customPars}


def get_page(comp, name):
    return next((pg for pg in comp.customPages if pg.name == name), None) \
        or comp.appendCustomPage(name)


def ensure_op(comp, optype, name, x, y):
    o = comp.op(name)
    if not o:
        o = comp.create(optype, name)
        o.nodeX, o.nodeY = x, y
    return o


def darken(rgb, amount=0.4):
    """Scale value only -- multiplying RGB uniformly leaves hue and saturation."""
    return tuple(c * (1.0 - amount) for c in rgb)


def set_color_par(o, prefix, rgb):
    """Set a 3-par colour tuplet like Fillcolorr/g/b. True if it existed."""
    names = {p.name for p in o.pars()}
    keys = [prefix + c for c in 'rgb']
    if not all(k in names for k in keys):
        return False
    for k, v in zip(keys, rgb):
        o.par[k].val = v
    return True


def sort_pages(comp):
    """Same tab order on every component, whichever pages it happens to have."""
    have = [pg.name for pg in comp.customPages]
    ordered = [n for n in PAGE_ORDER if n in have] + [n for n in have
                                                      if n not in PAGE_ORDER]
    try:
        comp.sortCustomPages(*ordered)
    except Exception as e:
        print(f'  !! {comp.path}: could not sort pages ({e})')


def mirror_menu(page, source_par, name, label):
    """A custom menu par cloning an operator's menu, bound back to it.

    TD does not expose a COMP's internal TOP Common parameters, so anything a
    user needs to reach has to be mirrored onto the component like this.
    """
    p = page.appendMenu(name, label=label)[0]
    p.menuNames = list(source_par.menuNames)
    p.menuLabels = list(source_par.menuLabels)
    current = source_par.menuNames[source_par.menuIndex]
    p.default = p.val = current
    source_par.expr = f'parent().par.{p.name}'
    return p


def set_order(o, index):
    """Connect Order on an In OP -- decides the component's connector order."""
    p = find_par(o, 'connectorder', 'connectionorder', 'order')
    if p is not None:
        p.val = index


def _toggle(o, *candidates):
    p = find_par(o, *candidates)
    if p is not None:
        p.val = True


def _read(rel):
    path = os.path.join(project.folder, HERE, rel)
    try:
        with open(path) as f:
            return f.read()
    except OSError:
        print(f'  !! cannot read {path}')
        return ''


# --- specs ------------------------------------------------------------------------

def load_specs():
    path = os.path.join(project.folder, HERE, 'hydra-functions.json')
    if not os.path.exists(path):
        return SLICE
    with open(path) as f:
        specs = json.load(f)

    # hydra-extensions.json adds inputs hydra itself does not have (see that
    # file). Kept separate so regenerating the upstream table cannot drop them.
    ext_path = os.path.join(project.folder, HERE, 'hydra-extensions.json')
    if os.path.exists(ext_path):
        with open(ext_path) as f:
            extensions = json.load(f)
        by_name = {s['name']: s for s in specs}
        for name, extra in extensions.items():
            if name.startswith('_') or name not in by_name:
                continue
            by_name[name]['inputs'] = by_name[name]['inputs'] + extra.get('inputs', [])
    return specs


def load_utils():
    """hydra-utils.glsl split on its `// ===== name =====` markers."""
    parts = re.split(r'^// =====\s*(\w+)\s*=====\s*$', _read('hydra-utils.glsl'),
                     flags=re.M)
    return {parts[i]: parts[i + 1].strip() for i in range(1, len(parts) - 1, 2)}


def store_spec(comp, spec, utils):
    """Everything hydra_compile needs to generate this component's shader.

    Storage survives .tox save/load, so a component -- and any chain it is
    compiled into -- needs neither the JSON nor any file, only this.
    """
    body = spec.get('glsl', '')
    comp.store('hydra_spec', {
        'name': spec['name'],
        'type': spec['type'],
        'inputs': spec['inputs'],
        'glsl': body,
        'utils': {u: utils[u] for u in UTILS
                  if u in utils and re.search(rf'\b{u}\b', body)},
        'uses': uses_of(spec),
        'alias': TEXTURE_ALIAS.get(spec['name']),
    })


# --- versions -----------------------------------------------------------------------

def compiler_hash():
    """Short hash of hydra_compile.py -- what the embedded `compile` DAT holds."""
    return hashlib.sha1(_read('hydra_compile.py').encode()).hexdigest()[:8]


VERSION_PARS = (('Version', 'version'), ('Compiler', 'compiler'), ('Built', 'built'))


def stamp_version(comp, chash=None):
    """Write the read-only Version page. Idempotent -- build and upgrade call it."""
    page = get_page(comp, 'Version')
    have = custom_names(comp)
    for name, label in VERSION_PARS:
        if name not in have:
            page.appendStr(name, label=label)
    values = {'Version': VERSION,
              'Compiler': (chash or compiler_hash()) if comp.op('compile') else '-',
              'Built': time.strftime('%Y-%m-%d %H:%M')}
    for name, value in values.items():
        p = comp.par[name]
        p.readOnly = False              # readOnly guards the UI; lift it to write
        p.val = value
        p.readOnly = True


def version_report(dest, depth=8):
    """List hydra components under `dest` not built from the current code."""
    chash = compiler_hash()
    found = _placed(dest, depth, need_glsl=False)
    stale = []
    for c in found:
        have = custom_names(c)
        v = c.par.Version.eval() if 'Version' in have else '(none)'
        h = c.par.Compiler.eval() if 'Compiler' in have else '(none)'
        if v != VERSION or (h not in ('-', chash)):
            stale.append(c)
            print(f'  {c.path}: version {v}, compiler {h}')
    print(f'current: version {VERSION}, compiler {chash} -- '
          f'{len(stale)} of {len(found)} component(s) stale'
          + (' -- run upgrade()' if stale else ''))
    return stale


# --- callbacks ----------------------------------------------------------------------

TIME_DEFAULT_EXPR = 'absTime.seconds'

CHAIN_EXEC = '''# OP Execute callbacks -- GENERATED by build_hydra, do not edit.
# Recompile this component (and what depends on it) when the chain changes.

def _c():
    return op('compile').module

def onWireChange(changeOp):
    _c().schedule(parent(), down=True, up=True)
    return

def onFlagChange(changeOp, *args):
    _c().schedule(parent(), down=False)    # the Viewer flag decides compiling
    return

def onNameChange(changeOp):
    _c().schedule(parent(), down=True)     # compiled chains refer to it by path
    return

def onPathChange(changeOp):
    _c().schedule(parent(), down=True)
    return
'''

MODE_EXEC = '''# Parameter Execute callbacks -- GENERATED by build_hydra, do not edit.

def onValueChange(par, prev):
    op('compile').module.schedule(parent(), down=True, up=True)
    return

def onPulse(par):
    op('compile').module.schedule(parent(), down=True, up=True)
    return
'''


def _exec_dat(comp, optype, name, x, text, pars):
    d = ensure_op(comp, optype, name, x, -450)
    d.text = text
    target = find_par(d, 'op', 'ops', 'operators')
    if target is not None:
        target.val = '..'
    if pars:
        which = find_par(d, 'pars', 'parameters', 'par')
        if which is not None:
            which.val = pars
    return d


def install_callbacks(comp, uses):
    """The `compile` module and the callbacks that drive it. Idempotent.

    Embedded rather than file-synced, so an exported .tox carries its own code.
    """
    ensure_op(comp, textDAT, 'compile', 200, -450).text = _read('hydra_compile.py')

    chain = _exec_dat(comp, opexecuteDAT, 'chain_exec', 400, CHAIN_EXEC, None)
    for t in ('wirechange', 'flagchange', 'namechange', 'pathchange'):
        _toggle(chain, t)

    mexec = _exec_dat(comp, parameterexecuteDAT, 'mode_exec', 600, MODE_EXEC,
                      'Mode Compile')
    _toggle(mexec, 'valuechange')
    _toggle(mexec, 'pulse', 'onpulse')

    if 'time' in uses:
        texec = _exec_dat(comp, parameterexecuteDAT, 'time_exec', -200,
                          _read('time_exec.py'), 'Propagatetime')
        _toggle(texec, 'pulse', 'onpulse')


# --- one component ------------------------------------------------------------------

# Leftovers of Coordinates mode and Seamless tiling (removed in 0.2.0) and of the
# file-synced shaders before them. Safe to delete once nothing older than 0.2.0
# is around -- `version_report` says.
LEGACY_PARS = ('Seamless', 'Seamwidth', 'Coordmode')
LEGACY_OPS = ('coords', 'pixel_compiled')


def _drop_legacy(comp):
    have = custom_names(comp)
    for name in LEGACY_PARS:
        if name in have:
            try:
                comp.par[name].destroy()
            except Exception as e:
                print(f'  !! {comp.path}: could not remove {name} ({e})')
    for name in LEGACY_OPS:
        o = comp.op(name)
        if o is not None:
            o.destroy()
    pixel = comp.op('pixel')
    if pixel and pixel.par.syncfile.eval():     # was synced to shader/<name>.frag
        pixel.par.syncfile = False
        pixel.par.file = ''


def _ensure_mode(page, comp):
    names = [n for n, _ in MODES]
    if 'Mode' not in custom_names(comp):
        m = page.appendMenu('Mode', label='mode')[0]
        m.menuNames, m.menuLabels = names, [l for _, l in MODES]
        m.default = m.val = names[0]
        return
    m = comp.par.Mode
    if list(m.menuNames) != names:
        current = m.eval()                       # `coords` maps to compiled
        m.menuNames, m.menuLabels = names, [l for _, l in MODES]
        m.default = names[0]
        m.val = current if current in names else names[0]


def ensure(comp, spec, utils=None, chash=None):
    """Give `comp` everything its spec needs, repairing what is stale.

    Idempotent: build() runs it on an empty COMP, upgrade() on a placed copy.
    An existing copy keeps its wiring, parameter values and node positions --
    only what is missing is created, and only generated content is rewritten.
    """
    utils = utils if utils is not None else load_utils()
    name, kind = spec['name'], spec['type']
    image_inputs = inputs_for(spec)
    floats = [i for i in spec['inputs'] if i['type'] == 'float']
    vecs = [i for i in spec['inputs'] if i['type'].startswith('vec')]
    uses = uses_of(spec)
    _drop_legacy(comp)
    have = custom_names(comp)

    # --- Hydra page: one parameter per argument -------------------------------
    if floats or vecs:
        page = get_page(comp, 'Hydra')
        for inp in floats:
            pn = par_name(inp['name'])
            if pn not in have:
                p = page.appendFloat(pn, label=inp['name'])[0]
                d = float(inp['default'] or 0)
                p.default = p.val = d
                p.normMin, p.normMax = min(0.0, 2 * d), max(1.0, 2 * d)
        for inp in vecs:                # only `sum` today; no CHOP input for these
            pn = par_name(inp['name'])
            if not any(n.startswith(pn) for n in have):
                width = int(inp['type'][3:])
                pars = page.appendFloat(pn, label=inp['name'], size=width)
                for p, v in zip(pars, inp['default'] or [0] * width):
                    p.default = p.val = float(v)

    # --- Time Sync: a parameter, not an input -- rarely rewired ---------------
    if 'time' in uses:
        tpage = get_page(comp, 'Time Sync')
        if 'Time' not in have:
            t = tpage.appendFloat('Time', label='time')[0]
            t.default = 0.0
            t.expr = TIME_DEFAULT_EXPR
        if 'Propagatetime' not in have:
            tpage.appendPulse('Propagatetime', label='Propagate Time Expr')

    # --- inputs: images first, then one CHOP per argument ---------------------
    for i, label in enumerate(image_inputs):
        set_order(ensure_op(comp, inTOP, label, -600, -160 * i), i)

    for k, inp in enumerate(floats):
        hn, y = inp['name'], 200 + 160 * k
        const = comp.op(f'{hn}_default')
        if not const:
            const = ensure_op(comp, constantCHOP, f'{hn}_default', -800, y)
            cname = find_par(const, 'name0', 'const0name')
            cvalue = find_par(const, 'value0', 'const0value')
            if cname is not None:
                cname.val = hn
            if cvalue is not None:
                cvalue.expr = f'parent().par.{par_name(hn)}'
        chop = ensure_op(comp, inCHOP, hn, -600, y)
        set_order(chop, len(image_inputs) + k)
        # The In CHOP's own input is the fallback, used when the component's
        # connector is empty -- the shader reads op('<arg>')[0] and relies on
        # it always having a channel. Builds differ on how many connectors it
        # exposes, so take the last one rather than assuming an index.
        if chop.inputConnectors:
            last = chop.inputConnectors[len(chop.inputConnectors) - 1]
            if not last.connections:
                last.connect(const)
        else:
            print(f'  !! {chop.path}: no input connectors to attach the default to')

    # --- shader DAT, GLSL TOP, Out TOP ---------------------------------------
    dat = ensure_op(comp, textDAT, 'pixel', -200, -300)
    glsl = comp.op('glsl')
    if not glsl:
        glsl = ensure_op(comp, glslTOP, 'glsl', 0, 0)
        set_menu(glsl.par.format, '16', 'float')
        set_menu(glsl.par.outputresolution, 'input' if image_inputs else 'custom')
    if glsl.par.pixeldat.eval() != dat:
        glsl.par.pixeldat = dat
    out = ensure_op(comp, outTOP, 'out', 250, 0)
    if not out.inputConnectors[0].connections:
        out.inputConnectors[0].connect(glsl)

    # --- Output page: mirrors of the GLSL TOP's Common parameters -------------
    opage = get_page(comp, 'Output')
    if not image_inputs:            # a source: nothing upstream to inherit from
        if not any(n.startswith('Resolution') for n in have):
            res_pars = opage.appendInt('Resolution', label='resolution', size=2)
            for p, v in zip(res_pars, DEFAULT_RES):
                p.default = p.val = v
            for gpar, cpar in zip(('resolutionw', 'resolutionh'), res_pars):
                p = find_par(glsl, gpar)
                if p is not None:
                    p.expr = f'parent().par.{cpar.name}'
    elif 'Inputsmoothness' not in have:   # only samplers care how input is read
        smooth = find_par(glsl, 'inputfiltertype', 'inputsmoothness', 'filtertype')
        if smooth is not None:
            mirror_menu(opage, smooth, 'Inputsmoothness', 'input smoothness')
    if 'Pixelformat' not in have:
        mirror_menu(opage, glsl.par.format, 'Pixelformat', 'pixel format')

    # --- Pipeline page ---------------------------------------------------------
    ppage = get_page(comp, 'Pipeline')
    _ensure_mode(ppage, comp)
    if 'Compile' not in have:
        ppage.appendPulse('Compile', label='Compile')

    # --- identity, code, version ------------------------------------------------
    viewer = find_par(comp, 'opviewer')
    if viewer is not None:
        viewer.val = './out'
    comp.color = GROUPS[kind][1]
    keep = {t for t in comp.tags if not t.startswith('hydra:') and t != HYDRA_TAG}
    comp.tags = keep | {HYDRA_TAG, f'hydra:fn:{name}', f'hydra:class:{kind}'}
    store_spec(comp, spec, utils)
    install_callbacks(comp, uses)
    stamp_version(comp, chash)
    sort_pages(comp)
    return comp


def compile_now(comp):
    """Generate the shader right away, rather than on the next frame."""
    c = comp.op('compile')
    if c:
        c.module.compile_now(comp)


def build(spec, dest, utils=None, chash=None):
    comp_name = f"hydra_{spec['name'].lower()}"
    old = dest.op(comp_name)
    if old:
        old.destroy()
    comp = ensure(dest.create(baseCOMP, comp_name), spec, utils, chash)
    compile_now(comp)
    print(f"{comp_name}: {spec['type']}, {len(inputs_for(spec))} TOP in, "
          f"{sum(i['type'] == 'float' for i in spec['inputs'])} CHOP in")
    return comp


AUDIO_COLOR = (0.94, 0.38, 0.60)      # the docs' Audio pink


def build_audio(dest):
    """hydra_fft: a.fft[n] as a component. Audio CHOP in, fft_0..fft_n out."""
    old = dest.op('hydra_fft')
    if old:
        old.destroy()
    comp = dest.create(baseCOMP, 'hydra_fft')

    page = comp.appendCustomPage('Hydra')
    specs = [('Bins', 'bins', 4, 1, 8), ('Cutoff', 'cutoff', 2.0, 0.0, 20.0),
             ('Scale', 'scale', 10.0, 0.01, 50.0), ('Smooth', 'smooth', 0.4, 0.0, 0.99),
             ('Buffer', 'buffer size', 512, 128, 4096)]
    for name, label, dflt, lo, hi in specs:
        p = (page.appendInt(name, label=label)[0] if isinstance(dflt, int)
             else page.appendFloat(name, label=label)[0])
        p.default = p.val = dflt
        p.normMin, p.normMax = lo, hi

    audio = comp.create(inCHOP, 'audio')
    audio.nodeX, audio.nodeY = -400, 0
    set_order(audio, 0)

    dat = comp.create(textDAT, 'fft_script')
    dat.par.file = f'{HERE}/fft_chop.py'
    dat.par.syncfile = True
    dat.par.loadonstart = True
    dat.nodeX, dat.nodeY = -200, -200

    script = comp.create(scriptCHOP, 'fft')
    script.nodeX, script.nodeY = 0, 0
    cb = find_par(script, 'callbacks', 'dat', 'script')
    if cb is not None:
        cb.val = dat.name
    script.inputConnectors[0].connect(audio)

    setup = find_par(script, 'setuppars', 'setupparameters')
    if setup is not None:
        setup.pulse()

    # bind the script's own pars to the component's, so users see one page
    for name, _, _, _, _ in specs:
        try:
            script.par[name].expr = f'parent().par.{name}'
        except Exception as e:
            print(f'  !! could not bind {name} on {script.path}: {e}')

    out = comp.create(outCHOP, 'out')
    out.nodeX, out.nodeY = 250, 0
    out.inputConnectors[0].connect(script)

    viewer = find_par(comp, 'opviewer')
    if viewer is not None:
        viewer.val = './out'
    comp.color = AUDIO_COLOR
    comp.tags = {HYDRA_TAG, 'hydra:fn:fft', 'hydra:class:audio'}
    stamp_version(comp)
    sort_pages(comp)
    print('hydra_fft: audio CHOP in, fft_0..fft_n + vol out')
    return comp

LIBRARY_PATH = None        # remembered by build_all, so spawn() needs no argument


def library(hint=None):
    """The container holding the generated components."""
    if hint is not None:
        return hint
    if LIBRARY_PATH and op(LIBRARY_PATH):
        return op(LIBRARY_PATH)
    try:                                   # nothing remembered: go looking
        found = root.findChildren(tags=[HYDRA_TAG], maxDepth=4)
    except Exception:
        found = []
    if found:
        return found[0].parent()
    print('  !! no hydra library found -- pass library=op(...)')
    return None


def unique_name(dest, base):
    if not dest.op(base):
        return base
    i = 1
    while dest.op(f'{base}{i}'):
        i += 1
    return f'{base}{i}'


def expand_names(names):
    """['osc*3', 'rotate'] -> ['osc', 'osc', 'osc', 'rotate'].

    Accepts a list or one whitespace-separated string, so both of these work:

        spawn(['osc*3', 'rotate'])
        spawn('osc*3 rotate scale')

    The count may sit on either side of the `*`, with or without spaces around
    it -- `osc*3`, `3*osc` and `osc * 3` are the same.
    """
    if isinstance(names, str):
        names = [names]
    flat = ' '.join(str(n) for n in names).replace('*', ' * ').split()

    out, i = [], 0
    while i < len(flat):
        token = flat[i]
        if token == '*':                       # '<a> * <b>' -- one of them is a count
            i += 1
            continue
        if i + 2 < len(flat) and flat[i + 1] == '*':
            a, b = token, flat[i + 2]
            if b.isdigit():
                out += [a] * int(b)
            elif a.isdigit():
                out += [b] * int(a)
            else:
                print(f'  !! cannot read a count in {a!r} * {b!r}')
            i += 3
            continue
        out.append(token)
        i += 1
    return out


def spawn(names, dest=None, lib=None, postfix='', spacing=200, x=0, y=0):
    """Copy generated components by name, e.g. spawn(['osc', 'osc', 'rotate']).

    Counts are supported: spawn(['osc*3', 'rotate']) or spawn('osc*3 rotate').

    Repeats are fine -- each copy gets a numeric suffix so names stay unique.
    `postfix` goes before that suffix: postfix='_a' gives hydra_osc_a.

    Copies land in `dest`, defaulting to the library's parent rather than the
    library itself: copies inherit the `hydra` tag, and clear()/rebuild() would
    destroy them along with the originals if they sat in the same container.
    """
    lib = library(lib)
    if lib is None:
        return []
    dest = dest or lib.parent()

    made, missing = [], []
    for i, name in enumerate(expand_names(names)):
        original = lib.op(f'hydra_{name.lower()}')
        if not original:
            missing.append(name)
            continue
        copy = dest.copy(original, name=unique_name(dest, f'hydra_{name.lower()}{postfix}'))
        copy.nodeX, copy.nodeY = x + spacing * len(made), y
        compile_now(copy)                  # its own shader, not the original's
        made.append(copy)

    print(f'spawned {len(made)} in {dest.path}: ' + ', '.join(c.name for c in made))
    if missing:
        print('  !! not in the library:', ', '.join(missing))
    return made

def spec_name(comp, by_name):
    """Which hydra function a placed component is, despite renaming.

    The node name comes first: it is what the user sees, and copies only mangle
    it in two predictable ways -- TD appends digits on collision (hydra_osc3),
    users append their own suffixes (hydra_scrollx_rangga3x). The `hydra:fn:`
    tag is the fallback.
    """
    base = comp.name[len('hydra_'):] if comp.name.startswith('hydra_') else comp.name
    for candidate in (base,
                      base.rstrip('0123456789'),
                      base.split('_')[0],
                      base.split('_')[0].rstrip('0123456789')):
        if candidate.lower() in by_name:
            return candidate.lower()
    for t in comp.tags:
        if t.startswith('hydra:fn:'):
            candidate = t.split(':', 2)[2].lower()
            if candidate in by_name:
                return candidate
    return None


def _placed(dest, depth=8, need_glsl=True):
    """Hydra components under `dest`. Untagged `hydra_*` COMPs with a `glsl`
    count too -- copies made before tagging existed."""
    try:
        found = dest.findChildren(type=COMP, maxDepth=depth)
    except Exception:
        found = [c for c in dest.children if c.isCOMP]
    return [c for c in found
            if (HYDRA_TAG in c.tags or c.name.startswith('hydra_') and c.op('glsl'))
            and (c.op('glsl') or not need_glsl)]


def upgrade(dest, specs=None, depth=8):
    """Bring every hydra component under `dest` up to the current code, in place.

    Runs the same ensure() as build, so a placed copy ends up exactly as a fresh
    build would make it -- minus anything you changed: wiring, parameter values
    and node positions are kept. Then regenerates its shader.

    Searches recursively, so point it at a project or a patch container, not
    just the library.
    """
    specs = specs or load_specs()
    by_name = {s['name'].lower(): s for s in specs}
    utils, chash = load_utils(), compiler_hash()

    fixed, skipped, failed, retired = [], [], [], []
    for comp in _placed(dest, depth, need_glsl=False):
        if comp.name.startswith('hydra_fft'):
            stamp_version(comp, chash)          # built by build_audio, has no spec
            sort_pages(comp)
            continue
        name = spec_name(comp, by_name)
        if name is None:
            (retired if comp.name.startswith('hydra_coords') else skipped) \
                .append(comp.path)
            continue
        try:
            ensure(comp, by_name[name], utils, chash)
            compile_now(comp)
            fixed.append(comp.name)
        except Exception as e:                  # never let one bad comp stop the sweep
            failed.append(f'{comp.path} ({e})')

    print(f'upgraded {len(fixed)} component(s) under {dest.path} to {VERSION}')
    if retired:
        print('  hydra_coords is gone with Coordinates mode -- delete:', ', '.join(retired))
    if skipped:
        print('  !! could not identify:', ', '.join(skipped))
    if failed:
        print('  !! errored:', '; '.join(failed))
    return fixed


def set_mode(dest, mode, depth=8):
    """Set Mode on every hydra component under `dest`: 'compiled' or 'image'.

    Each change triggers its own recompile, collapsed to one per frame.
    """
    changed = []
    for c in _placed(dest, depth):
        if 'Mode' in custom_names(c) and mode in c.par.Mode.menuNames:
            c.par.Mode = mode
            changed.append(c.name)
    print(f'Mode = {mode} on {len(changed)} component(s)')
    return changed


def cook_report(dest, depth=8):
    """Last-frame CPU and GPU cook times of every hydra GLSL TOP under `dest`.

    Components that did not cook this frame report 0 -- that is the saving of
    Compiled mode: only outputs and viewed components cook.
    """
    rows, cpu, gpu = [], 0.0, 0.0
    for c in _placed(dest, depth):
        g = c.op('glsl')
        ct, gt = getattr(g, 'cookTime', 0.0), getattr(g, 'gpuCookTime', 0.0)
        if getattr(g, 'cookFrame', -1) < absTime.frame - 1:
            ct = gt = 0.0
        cpu, gpu = cpu + ct, gpu + gt
        mode = c.par.Mode.eval() if 'Mode' in custom_names(c) else '-'
        rows.append((c.path, mode, ct, gt))
    for path, mode, ct, gt in sorted(rows, key=lambda r: -r[3]):
        print(f'{gt:8.3f} ms gpu {ct:8.3f} ms cpu  {mode:9} {path}')
    print(f'total: {gpu:.3f} ms gpu, {cpu:.3f} ms cpu over {len(rows)} component(s)')
    return gpu, cpu


def set_resolution(dest, width, height):
    """Retune every generated source component's output resolution."""
    n = 0
    for child in dest.children:
        if HYDRA_TAG not in child.tags:
            continue
        pars = sorted(child.pars('Resolution*'), key=lambda p: p.name)
        if len(pars) >= 2:
            pars[0].val, pars[1].val = width, height
            n += 1
    print(f'set {n} source component(s) to {width}x{height}')
    if max(width, height) > NONCOMMERCIAL_MAX:
        print(f'  !! over {NONCOMMERCIAL_MAX}px -- a non-commercial licence will '
              f'clamp this')
    return n


def set_output(dest, smoothness=None, pixel_format=None):
    """Set Input Smoothness / Pixel Format across a container, by substring.

        set_output(dest, smoothness='nearest')
        set_output(dest, pixel_format='8-bit')

    Matching is on the menu entry text, so partial names are fine; anything that
    does not match prints its available options.
    """
    smoothed = formatted = 0
    for child in dest.children:
        if HYDRA_TAG not in child.tags:
            continue
        if smoothness and 'Inputsmoothness' in {p.name for p in child.pars()}:
            set_menu(child.par.Inputsmoothness, smoothness.lower())
            smoothed += 1
        if pixel_format and 'Pixelformat' in {p.name for p in child.pars()}:
            set_menu(child.par.Pixelformat, *pixel_format.lower().split())
            formatted += 1
    if smoothness:
        print(f'set input smoothness on {smoothed} component(s)')
    if pixel_format:
        print(f'set pixel format on {formatted} component(s)')


def is_annotate(o):
    return getattr(o, 'OPType', '') == 'annotateCOMP' or o.name.startswith('group_')


def clear(dest, components=True, annotations=True):
    """Destroy generated ops in `dest`.

    DESTRUCTIVE: removes every `hydra_*` COMPONENT and every Annotate COMP in
    that container, including annotations you added by hand. Scoped to `dest`,
    so keep the hydra components in their own container.

    Only COMPs are touched. Helper DATs living alongside them -- `hydra_seq`
    notably -- are named `hydra_*` too and must survive.
    """
    removed = []
    for child in list(dest.children):
        if components and child.isCOMP and (HYDRA_TAG in child.tags
                                            or child.name.startswith('hydra_')):
            removed.append(child.name)
            child.destroy()
        elif annotations and is_annotate(child):
            removed.append(child.name)
            child.destroy()
    print(f'cleared {len(removed)} ops from {dest.path}')
    return removed


def rebuild(dest, specs=None):
    """Wipe everything generated, then build it all again from the JSON."""
    clear(dest)
    return build_all(dest, specs)


def layout_groups(dest, specs, verbose=True):
    """Arrange components by hydra doc group, each wrapped in an Annotate COMP."""
    for child in list(dest.children):        # stale annotations from earlier runs
        if is_annotate(child):
            child.destroy()

    by_kind = {}
    for s in specs:
        by_kind.setdefault(s['type'], []).append(s)
    for kind, members in EXTRA_MEMBERS.items():          # only if actually built
        present = [m for m in members if dest.op(f"hydra_{m['name'].lower()}")]
        if present:
            by_kind.setdefault(kind, []).extend(present)

    top = 0
    for kind in GROUP_ORDER:
        items = by_kind.get(kind, [])
        if not items:
            continue
        label, col = GROUPS[kind]
        rows = (len(items) + COLS - 1) // COLS
        cols = min(len(items), COLS)

        placed = []
        for i, spec in enumerate(items):
            comp = dest.op(f"hydra_{spec['name'].lower()}")
            if not comp:
                continue
            r, c = divmod(i, COLS)
            comp.nodeX = c * CELL_W
            comp.nodeY = top - r * CELL_H
            placed.append(comp)

        note = dest.create(annotateCOMP, f'group_{kind.lower()}')
        if verbose and kind == GROUP_ORDER[0]:
            print('annotateCOMP pars:', sorted(p.name for p in note.pars()))

        title = find_par(note, 'Title', 'Titletext', 'title', 'titletext', 'header')
        if title is not None:
            title.val = label
        body = find_par(note, 'Bodytext', 'Body', 'Text', 'Notes', 'message')
        if body is not None:
            body.val = f'hydra {label} -- {len(items)} functions'

        note.color = col                      # header keeps the full group colour
        if verbose and kind == GROUP_ORDER[0]:
            print('annotate colour pars:',
                  sorted(p.name for p in note.pars() if 'color' in p.name.lower()))
        for prefix in ('Backcolor', 'Fillcolor', 'Bgcolor', 'Bodycolor'):
            if set_color_par(note, prefix, darken(col, 0.4)):
                break
        else:
            print(f'  !! {note.path}: no fill-colour par found for the body')

        # nodeY is the node's BOTTOM edge, height grows upward -- derive the
        # rectangle from what was actually placed rather than from the grid
        if placed:
            x0 = min(c.nodeX for c in placed)
            x1 = max(c.nodeX + c.nodeWidth for c in placed)
            y0 = min(c.nodeY for c in placed)
            y1 = max(c.nodeY + c.nodeHeight for c in placed)
            note.nodeX, note.nodeY = x0 - PAD, y0 - PAD
            note.nodeWidth = (x1 - x0) + 2 * PAD
            note.nodeHeight = (y1 - y0) + 2 * PAD

        top -= rows * CELL_H + PAD * 3
    print('laid out', len(specs), 'components in', len(GROUP_ORDER), 'groups')


def members(specs):
    """[(group kind, function name)] for everything that should exist."""
    out = [(s['type'], s['name']) for s in specs]
    for kind, extra in EXTRA_MEMBERS.items():
        out += [(kind, m['name']) for m in extra]
    return out


def export_tox(dest, specs=None, root=None, group_case=str.lower):
    """Save each component to <root>/<group>/hydra_<name>.tox.

    Overwrites whatever is there, so the tree always matches the last build.
    """
    specs = specs or load_specs()
    root = root or os.path.join(project.folder, *TOX_ROOT.split('/'))

    saved, missing = 0, []
    for kind, name in members(specs):
        comp = dest.op(f'hydra_{name.lower()}')
        if not comp:
            missing.append(name)
            continue
        folder = os.path.join(root, group_case(GROUPS[kind][0]))
        os.makedirs(folder, exist_ok=True)
        comp.save(os.path.join(folder, f'hydra_{name.lower()}.tox'))
        saved += 1

    print(f'saved {saved} .tox files under {root}')
    if missing:
        print('  not built, skipped:', ', '.join(missing))
    return saved


def palette_root():
    """The user palette folder -- what the Palette browser lists as My Components."""
    config = getattr(app, 'configFolder', None)
    candidates = [getattr(app, 'userPaletteFolder', None),
                  os.path.join(config, 'Palette') if config else None,
                  os.path.expanduser('~/Documents/Derivative/Palette')]
    for c in candidates:
        if c and os.path.isdir(c):
            return c
    fallback = os.path.expanduser('~/Documents/Derivative/Palette')
    print(f'  !! no palette folder among {[c for c in candidates if c]}')
    print(f'  !! creating {fallback} -- pass root=... if your palette is elsewhere')
    return fallback


def export_palette(dest, specs=None, root=None, section='Hydra'):
    """Save into the user palette as My Components/Hydra/<Group>/hydra_<name>."""
    root = os.path.join(root or palette_root(), section)
    n = export_tox(dest, specs, root=root, group_case=lambda g: g)
    print('  refresh the Palette pane to pick up changes')
    return n


def build_all(dest, specs=None, layout=True, audio=True, tox=True, palette=True):
    global LIBRARY_PATH
    LIBRARY_PATH = dest.path           # so spawn() can find the library later
    specs = specs or load_specs()
    utils, chash = load_utils(), compiler_hash()
    for spec in specs:
        build(spec, dest, utils, chash)
    if audio:
        build_audio(dest)
    if layout:
        layout_groups(dest, specs)
    if tox:
        export_tox(dest, specs)
    if palette:
        export_palette(dest, specs)
    print(f'built {len(specs)} components in {dest.path}')
