"""Write one TouchDesigner .frag per hydra function, from hydra-functions.json.

Each shader is: uniforms, any utility functions the body calls, the hydra
function itself (signature from its class, body verbatim), and a main() that
adapts the class to TD's GLSL TOP conventions.

Run standalone:

    python3 assets/scripts/hydra/emit_frags.py

or from a TD Text DAT synced to this file:

    mod('/project1/hydra/emit_frags').emit_all()

Bodies are copied character for character from hydra. Everything else in the
file is generated, so regenerating after a hydra update is safe -- do not hand
edit the output.
"""

import json
import os
import re

# --- class -> GLSL signature and main() --------------------------------------
# (leading args of the hydra function, before its own inputs)
SIGNATURE = {
    'src':          ('vec4', ['vec2 _st']),
    'coord':        ('vec2', ['vec2 _st']),
    'color':        ('vec4', ['vec4 _c0']),
    'combine':      ('vec4', ['vec4 _c0', 'vec4 _c1']),
    'combineCoord': ('vec2', ['vec2 _st', 'vec4 _c0']),
}

MAIN = {
    'src': """void main() {{
   fragColor = TDOutputSwizzle({name}(vUV.st{args}));
}}""",
    'coord': """void main() {{
   // a coord node samples its input at the transformed coordinate;
   // fract() stands in for hydra's wrap, which happens inside src()/prev()
   vec2 st = {name}(vUV.st{args});
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st)));
}}""",
    'color': """void main() {{
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle({name}(c0{args}));
}}""",
    'combine': """void main() {{
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);   // source
   vec4 c1 = texture(sTD2DInputs[1], vUV.st);   // with
   fragColor = TDOutputSwizzle({name}(c0, c1{args}));
}}""",
    'combineCoord': """void main() {{
   vec2 st = vUV.st;
   vec4 c0 = texture(sTD2DInputs[1], st);       // modulator (hydra's _c0)
   vec2 st2 = {name}(st, c0{args});
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st2)));
}}""",
}

# functions whose hydra body samples a named texture -- map it onto a TOP input
TEXTURE_ALIAS = {
    'src':  ('tex', 'sTD2DInputs[0]'),
    'prev': ('prevBuffer', 'sTD2DInputs[0]'),
}

UTILS = ('_luminance', '_noise', '_rgbToHsv', '_hsvToRgb')


SHADER_DIR = 'shader'      # .frag files and _utils.glsl live here


def _here():
    """Directory of this script, whether run by python3 or as a TD DAT module."""
    try:
        return os.path.dirname(os.path.abspath(__file__))
    except NameError:
        return os.path.join(project.folder, 'assets', 'scripts', 'hydra')


def load_utils(path):
    """Split _utils.glsl on its `// ===== name =====` markers."""
    with open(path) as f:
        text = f.read()
    parts = re.split(r'^// =====\s*(\w+)\s*=====\s*$', text, flags=re.M)
    # parts: [preamble, name, body, name, body, ...]
    return {parts[i]: parts[i + 1].strip() for i in range(1, len(parts) - 1, 2)}


def glsl_default(inp):
    d = inp['default']
    if isinstance(d, list):
        return f"{inp['type']}({', '.join(f'{float(v)}' for v in d)})"
    return 'null' if d is None else f'{float(d)}'


def emit(spec, utils):
    name, kind = spec['name'], spec['type']
    ret, lead = SIGNATURE[kind]
    inputs = spec['inputs']
    body = spec['glsl']

    out = [
        f'// hydra `{name}` -- type: {kind}',
        '// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.',
    ]
    if inputs:
        args = ', '.join(f"{i['name']} ({glsl_default(i)})" for i in inputs)
        out.append(f'// inputs: {args}')
    out.append('')

    # --- uniforms -------------------------------------------------------------
    uniforms = []
    if re.search(r'\btime\b', body):
        uniforms.append('uniform float time;          // -> absTime.seconds')
    if re.search(r'\bresolution\b', body):
        uniforms.append('uniform vec2 resolution;     // -> me.width, me.height')
    alias = TEXTURE_ALIAS.get(name)
    for i in inputs:
        if alias and i['name'] == alias[0]:
            continue                                   # becomes a TOP input
        if i['type'] in ('float', 'vec2', 'vec3', 'vec4'):
            uniforms.append(f"uniform {i['type']} {i['name']};")
        else:
            out.append(f"// !! unhandled input type {i['type']} for {i['name']}")
    if uniforms:
        out += uniforms + ['']

    if alias:
        out += [f'#define {alias[0]} {alias[1]}', '']
    if 'texture2D' in body:
        out += ['#define texture2D texture', '']

    out += ['out vec4 fragColor;', '']

    # --- utility functions the body calls -------------------------------------
    for u in UTILS:
        if re.search(rf'\b{u}\b', body):
            out += [f'// --- {u}, from hydra utility-functions.js ---',
                    utils[u], '']

    # --- the hydra function ---------------------------------------------------
    # `scrollX`, `scrollY` and `hue` each take an argument with the same name as
    # the function; in GLSL that parameter shadows the function and the shader
    # fails to compile. Rename the function, never the argument -- the body is
    # verbatim hydra and refers to the argument by name.
    fn = name
    if any(i['name'] == name for i in inputs):
        fn = f'hydra_{name}'
        out.append(f'// renamed from `{name}`: an argument shares that name')

    sig = lead + [f"{i['type']} {i['name']}" for i in inputs
                  if not (alias and i['name'] == alias[0])]
    out += [
        '// --- body verbatim from hydra glsl-functions.js ---',
        f"{ret} {fn}({', '.join(sig)}) {{",
        body.rstrip(),
        '}',
        '',
    ]

    # --- main() ---------------------------------------------------------------
    call_args = [i['name'] for i in inputs if not (alias and i['name'] == alias[0])]
    args = (', ' + ', '.join(call_args)) if call_args else ''
    out.append(MAIN[kind].format(name=fn, args=args))
    return '\n'.join(out) + '\n'


def emit_all(out_dir=None, json_path=None, utils_path=None, overwrite=True):
    here = _here()
    out_dir = out_dir or os.path.join(here, SHADER_DIR)
    json_path = json_path or os.path.join(here, 'hydra-functions.json')
    utils_path = utils_path or os.path.join(here, SHADER_DIR, '_utils.glsl')
    os.makedirs(out_dir, exist_ok=True)

    with open(json_path) as f:
        specs = json.load(f)
    utils = load_utils(utils_path)

    written, skipped = 0, []
    for spec in specs:
        path = os.path.join(out_dir, f"{spec['name']}.frag")
        if os.path.exists(path) and not overwrite:
            skipped.append(spec['name'])
            continue
        with open(path, 'w') as f:
            f.write(emit(spec, utils))
        written += 1
    print(f'wrote {written} shaders to {out_dir}')
    if skipped:
        print('skipped (already present):', ', '.join(skipped))
    return written


if __name__ == '__main__':
    emit_all()
