// hydra `layer` -- type: combine
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 layer(vec4 _c0, vec4 _c1) {
   return vec4(mix(_c0.rgb, _c1.rgb, _c1.a), clamp(_c0.a + _c1.a, 0.0, 1.0));
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);   // source
   vec4 c1 = texture(sTD2DInputs[1], vUV.st);   // with
   fragColor = TDOutputSwizzle(layer(c0, c1));
}
