// hydra `modulateRotate` -- type: combineCoord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: multiple (1.0), offset (0.0)

uniform float multiple;
uniform float offset;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 modulateRotate(vec2 _st, vec4 _c0, float multiple, float offset) {
   vec2 xy = _st - vec2(0.5);
   float angle = offset + _c0.x * multiple;
   xy = mat2(cos(angle),-sin(angle), sin(angle),cos(angle))*xy;
   xy += 0.5;
   return xy;
}

void main() {
   vec2 st = vUV.st;
   vec4 c0 = texture(sTD2DInputs[1], st);       // modulator (hydra's _c0)
   vec2 st2 = modulateRotate(st, c0, multiple, offset);
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st2)));
}
