// hydra `modulateRepeat` -- type: combineCoord
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: repeatX (3.0), repeatY (3.0), offsetX (0.5), offsetY (0.5)

uniform float repeatX;
uniform float repeatY;
uniform float offsetX;
uniform float offsetY;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec2 modulateRepeat(vec2 _st, vec4 _c0, float repeatX, float repeatY, float offsetX, float offsetY) {
   vec2 st = _st * vec2(repeatX, repeatY);
   st.x += step(1., mod(st.y,2.0)) + _c0.r * offsetX;
   st.y += step(1., mod(st.x,2.0)) + _c0.g * offsetY;
   return fract(st);
}

void main() {
   vec2 st = vUV.st;
   vec4 c0 = texture(sTD2DInputs[1], st);       // modulator (hydra's _c0)
   vec2 st2 = modulateRepeat(st, c0, repeatX, repeatY, offsetX, offsetY);
   fragColor = TDOutputSwizzle(texture(sTD2DInputs[0], fract(st2)));
}
