// hydra `src` -- type: src
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: tex (null)

#define tex sTD2DInputs[0]

#define texture2D texture

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 src(vec2 _st) {
   //  vec2 uv = gl_FragCoord.xy/vec2(1280., 720.);
   return texture2D(tex, fract(_st));
}

void main() {
   fragColor = TDOutputSwizzle(src(vUV.st));
}
