// hydra `sum` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: scale (vec4(1.0, 1.0, 1.0, 1.0))

uniform vec4 scale;

out vec4 fragColor;

// --- body verbatim from hydra glsl-functions.js ---
vec4 sum(vec4 _c0, vec4 scale) {
   vec4 v = _c0 * scale;
   return vec4(vec3(v.r + v.g + v.b + v.a), _c0.a);
   }
   float sum(vec2 _st, vec4 scale) { // vec4 is not a typo, because argument type is not overloaded
   vec2 v = _st.xy * scale.xy;
   return v.x + v.y;
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(sum(c0, scale));
}
