// hydra `thresh` -- type: color
// GENERATED by emit_frags.py from hydra-functions.json -- do not hand edit.
// inputs: threshold (0.5), tolerance (0.04)

uniform float threshold;
uniform float tolerance;

out vec4 fragColor;

// --- _luminance, from hydra utility-functions.js ---
float _luminance(vec3 rgb){
  const vec3 W = vec3(0.2125, 0.7154, 0.0721);
  return dot(rgb, W);
}

// --- body verbatim from hydra glsl-functions.js ---
vec4 thresh(vec4 _c0, float threshold, float tolerance) {
   return vec4(vec3(smoothstep(threshold-(tolerance+0.0000001), threshold+(tolerance+0.0000001), _luminance(_c0.rgb))), _c0.a);
}

void main() {
   vec4 c0 = texture(sTD2DInputs[0], vUV.st);
   fragColor = TDOutputSwizzle(thresh(c0, threshold, tolerance));
}
